### ISSUE TITLE
polardb-x(aliyun) failed to execute the create index statement

### ISSUE THREAD

**Issue by wanghangyu817** [zendesk/maxwell#1927] opened 2022-10-25 11:31 UTC
**Execute SQL ： CREATE INDEX device_id_idx ON event_tracking_info_extra (event, create_time)**

**Exception:**

```
31077 [DEBUG] C3P0PooledConnectionPool: Testing PooledConnection [com.mchange.v2.c3p0.impl.NewPooledConnection@38d72334] on CHECKOUT.
31078 [DEBUG] C3P0PooledConnectionPool: Test of PooledConnection [com.mchange.v2.c3p0.impl.NewPooledConnection@38d72334] on CHECKOUT has SUCCEEDED.
31085 [DEBUG] SchemaChange: SQL_PARSE <- "# POLARX_ORIGIN_SQL=CREATE INDEX device_id_idx ON event_tracking_info_extra (event, create_time)
# POLARX_TSO=xxxxx
CREATE INDEX device_id_idx ON event_tracking_info_extra (event, create_time)"
31156 [ERROR] MysqlParserListener: (statement CREATE INDEX device_id_idx ON event_tracking_info_extra ( event , create_time ))
31156 [ERROR] SchemaChange: Error parsing SQL: '# POLARX_ORIGIN_SQL=CREATE INDEX device_id_idx ON event_tracking_info_extra (event, create_time)
# POLARX_TSO=xxxxx
CREATE INDEX device_id_idx ON event_tracking_info_extra (event, create_time)'
31156 [ERROR] AbstractSchemaStore: Error on bin log position Position[BinlogPosition[binlog.000001:329876], lastHeartbeat=1666677625205]
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: CREATE
        at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:93)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:17)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:94)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:109)
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:50)
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:103)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:336)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:358)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:675)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:186)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:256)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:287)
31157 [INFO] BinlogConnectorReplicator: Binlog disconnected.
31158 [INFO] TaskManager: Stopping 3 tasks
31158 [ERROR] TaskManager: cause: 
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: CREATE
        at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:93) ~[maxwell-1.35.0.jar:1.35.0]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:17) ~[antlr4-runtime-4.8-1.jar:4.8-1]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28) ~[antlr4-runtime-4.8-1.jar:4.8-1]
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28) ~[antlr4-runtime-4.8-1.jar:4.8-1]
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:94) ~[maxwell-1.35.0.jar:1.35.0]
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:109) ~[maxwell-1.35.0.jar:1.35.0]
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:50) ~[maxwell-1.35.0.jar:1.35.0]
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:103) ~[maxwell-1.35.0.jar:1.35.0]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:336) ~[maxwell-1.35.0.jar:1.35.0]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:358) ~[maxwell-1.35.0.jar:1.35.0]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:675) ~[maxwell-1.35.0.jar:1.35.0]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:186) ~[maxwell-1.35.0.jar:1.35.0]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) ~[maxwell-1.35.0.jar:1.35.0]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:256) ~[maxwell-1.35.0.jar:1.35.0]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183) ~[maxwell-1.35.0.jar:1.35.0]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:287) ~[maxwell-1.35.0.jar:1.35.0]
31170 [INFO] TaskManager: Stopping: com.zendesk.maxwell.schema.PositionStoreThread@89866c7
31170 [DEBUG] StoppableTaskState: com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
31170 [INFO] TaskManager: Stopping: com.zendesk.maxwell.bootstrap.BootstrapController@1e486e4
31170 [DEBUG] StoppableTaskState: com.zendesk.maxwell.bootstrap.BootstrapController requestStop() called (in state: RUNNING)
31170 [INFO] TaskManager: Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@6300e18c
31170 [DEBUG] StoppableTaskState: com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: STOPPED)
31170 [DEBUG] TaskManager: Awaiting stop of: com.zendesk.maxwell.schema.PositionStoreThread@89866c7
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: CREATE
        at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:93)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:17)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:94)
        at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:109)
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:50)
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:103)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:336)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:358)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:675)
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:186)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:256)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:287)
31271 [DEBUG] TaskManager: Awaiting stop of: com.zendesk.maxwell.bootstrap.BootstrapController@1e486e4
31371 [DEBUG] TaskManager: Awaiting stop of: com.zendesk.maxwell.replication.BinlogConnectorReplicator@6300e18c
31471 [INFO] TaskManager: Stopped all tasks
```

**Comment by osheroff** [comment] 2022-11-01 23:57
what version of maxwell?  and can you recover the exact original SQL?

**Comment by wanghangyu817** [comment] 2022-11-02 02:41
I am currently using version 1.35.0, and when I test 1.38.0, I get the same error message, raw sql: `CREATE INDEX device_id_idx ON event_tracking_info_extra(event, create_time)`.  It is found in debug that a specific comment has been added to the executed sql, which is the cause of the error

**Comment by osheroff** [comment] 2022-11-02 13:14
can you run liike `show binlog events from ...` and recover the *exact* original SQL?  Your PR would just make it so that maxwell will never process *any* sql that contained a `# comment` style comment, which isn't right.  I can't reproduce your issue without the full, original sql (including comments.)

**Comment by wanghangyu817** [comment] 2022-11-02 13:24
![image](https://user-images.githubusercontent.com/18672877/199499849-50d5aa69-c12a-4316-9f9e-a926e027c34a.png)

I get sql :

```# POLARX_ORIGIN_SQL=CREATE INDEX device_id_idx ON event_tracking_info_extra (event, create_time)```
```# POLARX_TSO=698905756181096044815201227773638819850000000000000000```
```CREATE INDEX device_id_idx ON event_tracking_info_extra (event, create_time)```

![image](https://user-images.githubusercontent.com/18672877/199500812-ecdda114-00a5-4628-a3cb-2131fd23666c.png)

**Comment by wanghangyu817** [comment] 2022-11-02 13:31
If '--output_ddl=false' does the processing in pr solve the problem (which I'm using now and don't need to output ddl), or does the processing in pr cause other problems

**Comment by osheroff** [comment] 2022-11-02 13:33
no that won't solve your problem.

**Comment by wanghangyu817** [comment] 2022-11-02 13:39
I'm currently using pr code in a production environment, and I'm worried about other issues. I think only ddl statements go into this regular expression

**Comment by osheroff** [comment] 2022-11-02 14:19
fixed in latest

**Closed by osheroff** 2022-11-02 14:19 UTC
