### ISSUE TITLE
Error: 'Out of memory' occurring frequently in Production

### ISSUE THREAD

**Issue by rameshmm** [zendesk/maxwell#824] opened 2017-12-12 09:39 UTC
Hello,

We are using the worker for Maxwell with KPL  to read bin-log records. In production, we are getting frequent **Out of memory** issues (running on t2.micro with 1GB RAM). 

This is how heap dump looks on JVM crashes.
<img width="1407" alt="biggest_objects" src="https://user-images.githubusercontent.com/2418750/33876194-cce0d9d8-df4a-11e7-9099-eff0a7d08f24.png">
<img width="1222" alt="object_set" src="https://user-images.githubusercontent.com/2418750/33876193-cbac3d82-df4a-11e7-9269-e0072d0a63dd.png">

If possible, can you provide me any suggestions on the optimal JVM options and hardware requirements to avoid this error?

**Comment by osheroff** [comment] 2017-12-12 13:10
It looks like the rather unusually large schema of your database is perhaps the cause of the memory presume.  Would suggest bumping the JVM max heap size to at l least 500mb (-Xmx500m) and retrying .

**Comment by osheroff** [comment] 2017-12-26 09:58
closing this issue, please re-open if you have further problems.

**Closed by osheroff** 2017-12-26 09:58 UTC

**Comment by arungcs** [comment] 2018-03-11 23:11
We found that this issue could also happen when your /tmp space gets filled up... we worked around the problem by changing where the "evict" method writes temp file (default is "/tmp")... 

You can do that by specifying the "`-Djava.io.tmpdir=/not-root-filesystem/tmp`" when starting maxwell
