### ISSUE TITLE
Zendesk crashes if there is period in column in Create Table statment

### ISSUE THREAD

**Issue by tomarkuntal** [zendesk/maxwell#204] opened 2015-12-16 03:11 UTC
When executing following SQL Statement, maxwell crashes if there is dot (period) in column names. If I modify to test.CreatedBy to test_CreatedBy everything works fine. I understand having period in column name is not the right way but that is the convention that is being used right now.

SQL statement:

CREATE TABLE `person_5654e0fa181c13df04000020` (
  `_id` varchar(45) NOT NULL,
  `test.CreatedBy` varchar(45) DEFAULT NULL,
  `firstName` varchar(255) DEFAULT NULL,
  `lastName` varchar(255) DEFAULT NULL,
  `startDate` datetime DEFAULT NULL,
  `isActive` int(1) DEFAULT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

Error in maxwell:

03:00:28,073 DEBUG SchemaChange - SQL_PARSE <- "CREATE TABLE `person_5654e0fa181c13df04000020` (
  `_id` varchar(45) NOT NULL,
  `test.CreatedBy` varchar(45) DEFAULT NULL,
  `firstName` varchar(255) DEFAULT NULL,
  `lastName` varchar(255) DEFAULT NULL,
  `startDate` datetime DEFAULT NULL,
  `isActive` int(1) DEFAULT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1"
03:00:28,084 ERROR MysqlParserListener - (data_type ` varchar(45) DEFAULT NULL
03:00:28,085 ERROR SchemaChange - Error parsing SQL: 'CREATE TABLE `person_5654e0fa181c13df04000020` (
  `_id` varchar(45) NOT NULL,
  `test.CreatedBy` varchar(45) DEFAULT NULL,
  `firstName` varchar(255) DEFAULT NULL,
  `lastName` varchar(255) DEFAULT NULL,
  `startDate` datetime DEFAULT NULL,
  `isActive` int(1) DEFAULT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1'
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: ` varchar(45) DEFAULT NULL,
  `
	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:88)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:41)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:74)
	at com.zendesk.maxwell.MaxwellReplicator.processQueryEvent(MaxwellReplicator.java:288)
	at com.zendesk.maxwell.MaxwellReplicator.getRow(MaxwellReplicator.java:268)
	at com.zendesk.maxwell.MaxwellReplicator.work(MaxwellReplicator.java:89)
	at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:31)
	at com.zendesk.maxwell.Maxwell.run(Maxwell.java:91)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:97)
03:00:28,088 INFO  SchemaPosition - Storing final position: BinlogPosition[master.000001:76054]
03:00:28,088 DEBUG SchemaPosition - Writing binlog position to maxwell.positions: BinlogPosition[master.000001:76054]

**Comment by osheroff** [comment] 2015-12-16 04:12
Oh, I see.  I couldn't reproduce it, but github messed up the formatting after you posted it into the issue.

Correct me if I'm wrong, but the actual SQL should read:

```
CREATE TABLE `person_5654e0fa181c13df04000020` (
`_id` varchar(45) NOT NULL,
`test.CreatedBy` varchar(45) DEFAULT NULL,
...
```

with backtick characters, correct?

**Comment by tomarkuntal** [comment] 2015-12-16 04:21
Thanks for the quick response. Yes it was backticks. Just tested it again and it crashed.

SQL:

CREATE TABLE \`person_5654e0fa181c13df04000020\` (
\`_id\` varchar(45) NOT NULL,
\`test.CreatedBy\` varchar(45) DEFAULT NULL
)

Error:
SQL_PARSE <- "CREATE TABLE `person_5654e0fa181c13df04000020` (
\`_id\` varchar(45) NOT NULL,
\`test.CreatedBy\` varchar(45) DEFAULT NULL
)"
java.lang.NullPointerException
	at com.zendesk.maxwell.schema.ddl.MysqlParserListener.exitColumn_definition(MysqlParserListener.java:310)
	at com.zendesk.maxwell.schema.ddl.mysqlParser$Column_definitionContext.exitRule(mysqlParser.java:2528)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:71)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:54)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:74)
	at com.zendesk.maxwell.MaxwellReplicator.processQueryEvent(MaxwellReplicator.java:288)
	at com.zendesk.maxwell.MaxwellReplicator.getRow(MaxwellReplicator.java:268)
	at com.zendesk.maxwell.MaxwellReplicator.work(MaxwellReplicator.java:89)
	at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:31)
	at com.zendesk.maxwell.Maxwell.run(Maxwell.java:91)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:97)
04:18:29,134 INFO  SchemaPosition - Storing final position: BinlogPosition[master.000001:65614]
04:18:29,134 DEBUG SchemaPosition - Writing binlog position to maxwell.positions: BinlogPosition[master.000001:65614]

**Comment by osheroff** [comment] 2015-12-16 19:40
fixed in https://github.com/zendesk/maxwell/releases/tag/v0.16.2

**Closed by osheroff** 2015-12-16 19:40 UTC
