### ISSUE TITLE
How to do high availability  & maxwell

### ISSUE THREAD

**Issue by HelloDate** [zendesk/maxwell#1453] opened 2020-03-26 12:34 UTC
1, maxwell  have a high availability configuration？
2, what should i do when kafka upgrade

**Comment by osheroff** [comment] 2020-03-27 21:25
1.  It's not included in maxwell.  At Zendesk we used to use `consul lock`, and i'm sure mesos/kubernetes/AWS has their own form of offerings.  what platform do you run on?

**Comment by osheroff** [comment] 2020-03-27 21:25
2. shut down maxwell, upgrade kafka, restart maxwell

**Comment by osheroff** [comment] 2020-05-26 05:19
dupe of #1481

**Closed by osheroff** 2020-05-26 05:19 UTC
