### ISSUE TITLE
Maxwell connection mysql, idle connection timeout, maxwell process stops

### ISSUE THREAD

**Issue by saup007** [zendesk/maxwell#943] opened 2018-04-14 00:56 UTC
What is the default idle connection timeout, if it can be configured for less than 30 seconds and maxwell can retry the connection

I found that test is configured but main does not have this option

```
./src/test/java/com/zendesk/maxwell/MaxwellMysqlConfigTest.java

config.setJDBCOptions("autoReconnect=true&initialTimeout=2&maxReconnects=10");

```

MySQL idle connet timeout parameter

```
+----------------------------+----------+
| Variable_name              | Value    |
+----------------------------+----------+
| interactive_timeout        | 30       |
| wait_timeout               | 30       |
+----------------------------+----------+
```
maxwell log:
```
05:25:19,274 INFO  PositionStoreThread - Storing final position: Position[BinlogPosition[mysql-bin.001057:87907064], lastHeartbeat=0]
05:25:19,449 INFO  TaskManager - Stopping 3 tasks
05:25:19,449 ERROR TaskManager - cause:
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 30,012 milliseconds ago.  The last packet sent successfully to the server was 29,012 milliseconds ago.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:988) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3552) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3452) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3893) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5098) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at snaq.db.CachedPreparedStatement.executeUpdate(CachedPreparedStatement.java:151) ~[dbpool-7.0-jdk7.jar:?]
        at com.zendesk.maxwell.schema.MysqlPositionStore.heartbeat(MysqlPositionStore.java:142) ~[maxwell-1.13.1.jar:1.13.1]
        at com.zendesk.maxwell.schema.MysqlPositionStore.heartbeat(MysqlPositionStore.java:89) ~[maxwell-1.13.1.jar:1.13.1]
        at com.zendesk.maxwell.schema.MysqlPositionStore.heartbeat(MysqlPositionStore.java:83) ~[maxwell-1.13.1.jar:1.13.1]
        at com.zendesk.maxwell.schema.PositionStoreThread.work(PositionStoreThread.java:110) ~[maxwell-1.13.1.jar:1.13.1]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.13.1.jar:1.13.1]
        at com.zendesk.maxwell.schema.PositionStoreThread.run(PositionStoreThread.java:40) ~[maxwell-1.13.1.jar:1.13.1]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
        at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3004) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3462) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        ... 18 more
05:25:19,451 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@1cd5eda6
05:25:19,451 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: STOPPED)
05:25:19,451 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@18ea6ae4
05:25:19,451 INFO  StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
05:25:19,454 INFO  KafkaProducer - Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
05:25:19,463 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@55503ea3
05:25:19,464 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: RUNNING)
05:25:19,469 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
05:25:20,776 INFO  TaskManager - Stopped all tasks
05:25:20,777 ERROR Maxwell - SQLException: Communications link failure

The last packet successfully received from the server was 30,012 milliseconds ago.  The last packet sent successfully to the server was 29,012 milliseconds ago.
```

**Comment by osheroff** [comment] 2018-04-16 19:03
for now, you can set `autoReconnect` via --jdbc_options="autoReconnect=true".  In general, I guess we should be more resiliant with our jdbc connections and retry in these cases.

**Comment by dbapower** [comment] 2020-02-12 08:00
i use the autoReconnect in config file,but i hit the bug too.
here is the log:
18:47:56,630 INFO  AbstractSchemaStore - storing schema @Position[BinlogPosition[2151-binlog.000008:106253742], lastHeartbeat=1581418070114] after applying "DROP TABLE `tbl_experiment_config` /* generated by server */" to qdg_rta_online, new schema id is 97
22:10:12,858 INFO  TaskManager - Stopping 3 tasks
22:10:12,859 ERROR TaskManager - cause:
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 10,008 milliseconds ago.  The last packet sent successfully to the server was 7 milliseconds ago.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_101]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_101]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_101]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990) ~[mysql-connector-java-5.1.47.jar:5.1.47]
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3562) ~[mysql-connector-java-5.1.47.jar:5.1.47]
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3462) ~[mysql-connector-java-5.1.47.jar:5.1.47]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3905) ~[mysql-connector-java-5.1.47.jar:5.1.47]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495) ~[mysql-connector-java-5.1.47.jar:5.1.47]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903) ~[mysql-connector-java-5.1.47.jar:5.1.47]
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124) ~[mysql-connector-java-5.1.47.jar:5.1.47]
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058) ~[mysql-connector-java-5.1.47.jar:5.1.47]
        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158) ~[mysql-connector-java-5.1.47.jar:5.1.47]
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043) ~[mysql-connector-java-5.1.47.jar:5.1.47]
        at snaq.db.CachedPreparedStatement.executeUpdate(CachedPreparedStatement.java:151) ~[dbpool-7.0-jdk7.jar:?]
        at com.zendesk.maxwell.schema.MysqlPositionStore.heartbeat(MysqlPositionStore.java:142) ~[maxwell-1.19.7.jar:1.19.7]
        at com.zendesk.maxwell.schema.MysqlPositionStore.heartbeat(MysqlPositionStore.java:89) ~[maxwell-1.19.7.jar:1.19.7]
        at com.zendesk.maxwell.schema.MysqlPositionStore.heartbeat(MysqlPositionStore.java:83) ~[maxwell-1.19.7.jar:1.19.7]
        at com.zendesk.maxwell.schema.PositionStoreThread.work(PositionStoreThread.java:110) ~[maxwell-1.19.7.jar:1.19.7]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.19.7.jar:1.19.7]
        at com.zendesk.maxwell.schema.PositionStoreThread.run(PositionStoreThread.java:40) ~[maxwell-1.19.7.jar:1.19.7]
		        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
        at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3014) ~[mysql-connector-java-5.1.47.jar:5.1.47]
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3472) ~[mysql-connector-java-5.1.47.jar:5.1.47]
        ... 18 more
22:10:12,863 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@57050f5b
22:10:12,863 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: STOPPED)
22:10:12,863 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@59fd0abf
22:10:12,863 INFO  StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
22:10:12,865 INFO  KafkaProducer - [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
22:10:12,871 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@173ed8f1
22:10:12,872 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: RUNNING)
22:10:12,946 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
22:10:14,180 INFO  TaskManager - Stopped all tasks
22:10:14,180 ERROR Maxwell - SQLException: Communications link failure



-----here the maxwell proc crash,and i start it again------
The last packet successfully received from the server was 10,008 milliseconds ago.  The last packet sent successfully to the server was 7 milliseconds ago.
Using kafka version: 1.0.0
15:39:25,368 WARN  MaxwellMetrics - Metrics will not be exposed: metricsReportingType not configured.
15:39:25,876 INFO  ProducerConfig - ProducerConfig values:

**Comment by dbapower** [comment] 2020-02-12 08:04
here is the mysql timout config
`+-----------------------------+----------+
| Variable_name               | Value    |
+-----------------------------+----------+
| connect_timeout             | 10       |
| delayed_insert_timeout      | 300      |
| innodb_flush_log_at_timeout | 1        |
| innodb_lock_wait_timeout    | 30       |
| innodb_rollback_on_timeout  | OFF      |
| interactive_timeout         | 10       |
| lock_wait_timeout           | 31536000 |
| net_read_timeout            | 30       |
| net_write_timeout           | 60       |
| rpl_stop_slave_timeout      | 31536000 |
| slave_net_timeout           | 3600     |
| wait_timeout                | 10       |
+-----------------------------+----------+
12 rows in set (0.01 sec)`

here is the maxwell config:
`# options to pass into the jdbc connection, given as opt=val&opt2=val2
#jdbc_options=opt1=100&opt2=hello

jdbc_options=autoReconnect=true`

**Comment by dbapower** [comment] 2020-02-12 08:17
Is the jdbc_options=autoReconnect=true not available in config.properties?

**Comment by osheroff** [comment] 2020-12-15 21:56
i think i made maxwell much more durable to random connection failures in various threads awhile back.

**Closed by osheroff** 2020-12-15 21:56 UTC
